apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace | default "mysql-staging" }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: mysql
    port: {{ .Values.port }}
  clusterIP: None