mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: placeholder
    MYSQL_USER: placeholder
    MYSQL_PASSWORD: placeholder

todoapp:
  namespace: todoapp
  image:
    repository: orestprogrammer/todoapp
    tag: "5a466861c723eaab5ea8b7405242d3d9867471ab"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: zdfsadfsadfsfs
    DB_NAME: app_db
    DB_USER: app_user
    DB_PASSWORD: 1234
    DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"